### ISSUE TITLE
showing error Group matching query does not exist

### ISSUE THREAD

**Issue by 2fgdd** [rishank-shah/Exam-Portal#1]
while student or faculty login it is showing DoesNotExist at /faculty/login/
Group matching query does not exist. I tried solving the error but still facing same issue.

**Comment by rishank-shah** [comment]
Did you follow the steps mentioned in readme for [professor](https://github.com/rishank-shah/Exam-Portal#for-creating-accounts-for-professors-we-will-need-a-group-called-professor) .

![git](https://user-images.githubusercontent.com/75120859/112086478-4ef43980-8bb2-11eb-9874-35afeb7a8a72.PNG)

**Comment by 2fgdd** [comment]
yes now the problem is solved after doing this. 
thanks for the response
