### ISSUE TITLE
issues while submitting the exam(answers not getting saved after submitting)

### ISSUE THREAD

**Issue by 2fgdd** [rishank-shah/Exam-Portal#4]
when i click on submit button after giving exam. A notification pops up "do you want to leave the site? the changes you made may not be saved" and if i click on leave my answers are not getting saved and getting 0 in exams or if even the timers run out the answers are not getting saved.

**Comment by rishank-shah** [comment]
When you press on leave the site the answers are saved. Please check in database if answers are saved or not.
Did you specify the correct option while creating the question paper? Correct option should be in the form of option and not answer (eg: a, b, c, d)
Also check the python console if there are any errors.

**Comment by 2fgdd** [comment]
now the issue is solved .i was specifying the correct option in form of answer.
