### ISSUE TITLE
regarding mail

### ISSUE THREAD

**Issue by 2fgdd** [rishank-shah/Exam-Portal#5]
i am not receiving mail on professor email id if student opens another tab for more than 5 times.

**Comment by rishank-shah** [comment]
Please check if :
* You have Turned on Less Secure apps on your Gmail account.
* You have used correct email credentials in ```.env``` or ```env.bat``` file.
* You have used ```source .env``` or ```env.bat``` in the same terminal in which you are running ```python manage.py runserver```.
* If there are any errors in the terminal please provide a stacktrace of the error.

**Comment by nuts123w** [comment]
![image](https://user-images.githubusercontent.com/81586273/112883200-95362500-90eb-11eb-9aae-ac9882742a9f.png)
when I run env.batch file its showing syntax error what to do

**Comment by rishank-shah** [comment]
@nuts123w In the env.bat file after the = please put your own email credentials.
Please Note: The gmail account should have less secure apps on.
Example:
```
set EMAIL_HOST_PASSWORD=123456
set EMAIL_HOST_USER=abcd@gmail.com
set EMAIL_HOST=smtp.gmail.com
set DEFAULT_FROM_EMAIL=abcd@gmail.com
```

**Comment by nuts123w** [comment]
Thank you for your response ☺️
