### ISSUE TITLE
Email Not Working

### ISSUE THREAD

**Issue by mukeshbadgujar** [rishank-shah/Exam-Portal#6]
Exception Type: SMTPServerDisconnected at /faculty/reset-password/
Exception Value: please run connect() first

Please Give me Solution

**Comment by rishank-shah** [comment]
Please check -> issue #5 
If still error is not resolved then share the screenshot of the error.

**Comment by mukeshbadgujar** [comment]
Sorry My Mistake, 
Error Occurs Because i am not using proper env variables
I am writing wrong values.. so.... error occuring

EMAIL_BACKEND = 
EMAIL_HOST = 
EMAIL_USE_TLS = 
EMAIL_PORT = 
EMAIL_HOST_USER = 
EMAIL_HOST_PASSWORD =
